version: "3.3"

services:
#  sfp-mock:
#    container_name: sfp-mock
#    image: ekiauhce/sfp-mock:latest
#    env_file:
#      - .env
  postgres:
    container_name: sfp-mock-pg
    image: postgres:13.1-alpine
    env_file:
      - .env
    ports:
    - "5432:5432"